-- ============================================================================
-- AI Form Builder — schema DDL dump
-- ============================================================================
-- Generated by hand from database/migrations/* to match them exactly, since
-- this was built in a sandbox without a PHP/MySQL runtime available to run
-- `php artisan migrate` and `mysqldump` directly. Before relying on this file,
-- prefer regenerating it for real once you have the project running locally:
--
--   php artisan migrate --seed
--   mysqldump -u root -p form_builder --no-data > database/schema.sql
--   mysqldump -u root -p form_builder > database/full_dump.sql   # with seed data
--
-- Table order respects foreign key dependencies (tenants -> users -> forms ->
-- form_versions -> submissions -> submission_files, etc).
-- ============================================================================

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

-- ----------------------------------------------------------------------------
CREATE TABLE `tenants` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `slug` VARCHAR(255) NOT NULL,
  `settings` JSON NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `tenants_slug_unique` (`slug`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- ----------------------------------------------------------------------------
CREATE TABLE `users` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `tenant_id` BIGINT UNSIGNED NULL,
  `name` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `email_verified_at` TIMESTAMP NULL,
  `password` VARCHAR(255) NOT NULL,
  `role` VARCHAR(255) NOT NULL DEFAULT 'editor',
  `remember_token` VARCHAR(100) NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `users_email_unique` (`email`),
  KEY `users_tenant_id_foreign` (`tenant_id`),
  CONSTRAINT `users_tenant_id_foreign` FOREIGN KEY (`tenant_id`) REFERENCES `tenants` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- ----------------------------------------------------------------------------
CREATE TABLE `forms` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `uuid` CHAR(36) NOT NULL,
  `tenant_id` BIGINT UNSIGNED NULL,
  `owner_id` BIGINT UNSIGNED NULL,
  `title` VARCHAR(255) NOT NULL,
  `description` TEXT NULL,
  `slug` VARCHAR(40) NOT NULL,
  `status` ENUM('draft','published','archived') NOT NULL DEFAULT 'draft',
  `source` ENUM('manual','ai_generated','imported_docx','imported_xlsx') NOT NULL DEFAULT 'manual',
  `current_version_id` BIGINT UNSIGNED NULL,
  `accepts_submissions` TINYINT(1) NOT NULL DEFAULT 1,
  `closes_at` TIMESTAMP NULL,
  `submission_limit` INT UNSIGNED NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  `deleted_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `forms_uuid_unique` (`uuid`),
  UNIQUE KEY `forms_slug_unique` (`slug`),
  KEY `forms_tenant_id_status_index` (`tenant_id`, `status`),
  KEY `forms_owner_id_status_index` (`owner_id`, `status`),
  CONSTRAINT `forms_tenant_id_foreign` FOREIGN KEY (`tenant_id`) REFERENCES `tenants` (`id`) ON DELETE SET NULL,
  CONSTRAINT `forms_owner_id_foreign` FOREIGN KEY (`owner_id`) REFERENCES `users` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- ----------------------------------------------------------------------------
CREATE TABLE `form_versions` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `form_id` BIGINT UNSIGNED NOT NULL,
  `version_number` INT UNSIGNED NOT NULL,
  `schema` JSON NOT NULL,
  `created_via` ENUM('manual','ai_generate','ai_edit','import_docx','import_xlsx','rollback') NOT NULL DEFAULT 'manual',
  `change_summary` TEXT NULL,
  `created_by` BIGINT UNSIGNED NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `form_versions_form_id_version_number_unique` (`form_id`, `version_number`),
  KEY `form_versions_created_by_foreign` (`created_by`),
  CONSTRAINT `form_versions_form_id_foreign` FOREIGN KEY (`form_id`) REFERENCES `forms` (`id`) ON DELETE CASCADE,
  CONSTRAINT `form_versions_created_by_foreign` FOREIGN KEY (`created_by`) REFERENCES `users` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

ALTER TABLE `forms`
  ADD CONSTRAINT `forms_current_version_id_foreign`
  FOREIGN KEY (`current_version_id`) REFERENCES `form_versions` (`id`) ON DELETE SET NULL;

-- ----------------------------------------------------------------------------
CREATE TABLE `submissions` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `uuid` CHAR(36) NOT NULL,
  `form_id` BIGINT UNSIGNED NOT NULL,
  `form_version_id` BIGINT UNSIGNED NOT NULL,
  `payload` JSON NOT NULL,
  `submitter_ip` VARCHAR(45) NULL,
  `submitter_email` VARCHAR(255) NULL,
  `user_agent` VARCHAR(255) NULL,
  `status` ENUM('completed','partial') NOT NULL DEFAULT 'completed',
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `submissions_uuid_unique` (`uuid`),
  KEY `submissions_submitter_email_index` (`submitter_email`),
  KEY `submissions_form_id_created_at_index` (`form_id`, `created_at`),
  CONSTRAINT `submissions_form_id_foreign` FOREIGN KEY (`form_id`) REFERENCES `forms` (`id`) ON DELETE CASCADE,
  CONSTRAINT `submissions_form_version_id_foreign` FOREIGN KEY (`form_version_id`) REFERENCES `form_versions` (`id`) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- ----------------------------------------------------------------------------
CREATE TABLE `submission_files` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `submission_id` BIGINT UNSIGNED NOT NULL,
  `field_key` VARCHAR(255) NOT NULL,
  `original_name` VARCHAR(255) NOT NULL,
  `disk_path` VARCHAR(255) NOT NULL,
  `mime_type` VARCHAR(255) NOT NULL,
  `size_bytes` BIGINT UNSIGNED NOT NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  KEY `submission_files_submission_id_field_key_index` (`submission_id`, `field_key`),
  CONSTRAINT `submission_files_submission_id_foreign` FOREIGN KEY (`submission_id`) REFERENCES `submissions` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- ----------------------------------------------------------------------------
CREATE TABLE `ai_generation_logs` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `uuid` CHAR(36) NOT NULL,
  `form_id` BIGINT UNSIGNED NULL,
  `requested_by` BIGINT UNSIGNED NULL,
  `type` ENUM('generate','edit') NOT NULL,
  `prompt` TEXT NOT NULL,
  `input_schema` JSON NULL,
  `status` ENUM('pending','processing','succeeded','failed') NOT NULL DEFAULT 'pending',
  `attempt` TINYINT UNSIGNED NOT NULL DEFAULT 1,
  `error` TEXT NULL,
  `model` VARCHAR(255) NULL,
  `prompt_tokens` INT UNSIGNED NULL,
  `completion_tokens` INT UNSIGNED NULL,
  `latency_ms` INT UNSIGNED NULL,
  `output_schema` JSON NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `ai_generation_logs_uuid_unique` (`uuid`),
  KEY `ai_generation_logs_status_created_at_index` (`status`, `created_at`),
  CONSTRAINT `ai_generation_logs_form_id_foreign` FOREIGN KEY (`form_id`) REFERENCES `forms` (`id`) ON DELETE SET NULL,
  CONSTRAINT `ai_generation_logs_requested_by_foreign` FOREIGN KEY (`requested_by`) REFERENCES `users` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- ----------------------------------------------------------------------------
CREATE TABLE `form_imports` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `uuid` CHAR(36) NOT NULL,
  `form_id` BIGINT UNSIGNED NULL,
  `uploaded_by` BIGINT UNSIGNED NULL,
  `original_filename` VARCHAR(255) NOT NULL,
  `disk_path` VARCHAR(255) NOT NULL,
  `file_type` ENUM('docx','xlsx') NOT NULL,
  `status` ENUM('queued','processing','needs_review','committed','failed') NOT NULL DEFAULT 'queued',
  `draft_schema` JSON NULL,
  `unparsed_blocks` JSON NULL,
  `error` TEXT NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `form_imports_uuid_unique` (`uuid`),
  CONSTRAINT `form_imports_form_id_foreign` FOREIGN KEY (`form_id`) REFERENCES `forms` (`id`) ON DELETE SET NULL,
  CONSTRAINT `form_imports_uploaded_by_foreign` FOREIGN KEY (`uploaded_by`) REFERENCES `users` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

SET FOREIGN_KEY_CHECKS = 1;
